
```{r}
library(lubridate)
library(scales)
library(dplyr)
library(tidyr)
library(ggplot2)
```
```{r}
df = read.csv('C:/Users/Lenovo/Downloads/Auto Sales data.csv')

head(df,1)
```


```{r}
# relevant variables to be considered : sales, order date, status, product line, country, deal size
df = df[,c('SALES','ORDERDATE','STATUS','PRODUCTLINE','COUNTRY','DEALSIZE' )]
str(df)
```
```{r}
# correcting data structures
df$ORDERDATE = as.Date(df$ORDERDATE, format("%d/%m/%Y"))
df$STATUS = as.factor(df$STATUS)
df$PRODUCTLINE = as.factor(df$PRODUCTLINE)
df$COUNTRY = as.factor(df$COUNTRY)
df$DEALSIZE = as.factor(df$DEALSIZE)
str(df)
# Data profiling
# Create a summary of the data, including the distribution, range, and frequency of each variable
summary(df)
```
```{r}
# Data standardization
# Convert sales to z-scores
zscores = scale(df$SALES)
df$SALES_ZSCORES = zscores

# Data aggregation
# Calculate average sales for each product line
average_sales_by_product_line = aggregate(df$SALES, by = list(df$PRODUCTLINE), FUN = mean)
names(average_sales_by_product_line) = c('PRODUCTLINE', 'AVERAGE_SALES')

```
```{r}
# 1. summary stats of sales

#What is the minimum, maximum, and average sales over the 3 years?
#What is the standard deviation of sales?
#What is the median sales?


summary(df$SALES)
# minimum sales over 3 years = 482.1
# maximum sales over 3 years = 14082.8
# average sales over 3 years = 3553

```
```{r}
#2Range of dates:

#What is the earliest and latest order date in the data set?
#How long of a period does the data set cover?
min(df$ORDERDATE)
max(df$ORDERDATE)
# we have data from Jan 2018 to May 2020

# Plot the distribution of order dates
ggplot(df, aes(x = ORDERDATE)) +
  geom_histogram(binwidth = 10) +
  labs(title = "Distribution of Order Dates", x = "Order Date", y = "Number of Orders")


```

```{r}

# 3. Status distribution 

#What proportion of orders are shipped, cancelled, disputed, or on hold?
#What is the overall efficiency of the business, based on the order status distribution?
round(prop.table(table(df$STATUS))*100,1)

# Create a bar chart to visualize the order status distribution
ggplot(df, aes(x = STATUS)) +
  geom_bar(stat = "count", fill = "steelblue") +
  labs(title = "Distribution of Order Statuses", x = "Order Status", y = "Number of Orders")

```

```{r}

# 4. Product line distribution:

#What is the proportion of sales generated by each product line (classic cars, vintage cars, trucks-n-buses, motorcycles, trains, aircraft, ships)?
#Which product line is the most profitable?
round(prop.table(table(df$PRODUCTLINE))*100,1)

 #Distribution of sales across product lines:
#what is the distribution of sales across different product lines?
#Which product line has the highest average sales?
#Which product line has the most volatile sales?

ggplot(df, aes(x=PRODUCTLINE, y=SALES, fill=PRODUCTLINE))+
  geom_boxplot()+
  labs(title = 'Sales vs Product Lines', x='Product Line',y='Sales')



```


```{r}
# 5. Deal size distribution:

#What proportion of orders are classified as small, medium, or large?
#How common are large orders?
round(prop.table(table(df$DEALSIZE))*100,1)
# large order comprise of 5.5% of the total orders dealt with
# mostly we deal in medium to small sized orders - reflects the nature and volume of business 



# What is the proportion of different deal sizes?

#How many orders fall into each deal size category (small, medium, large)?
#What is the relative frequency of each deal size category?
ggplot(df, aes(x = DEALSIZE, fill = DEALSIZE)) +
  geom_bar(stat = "count", show.legend = FALSE) +
  labs(title = "Proportion of Deal Sizes", x = "Deal Size", y = "Count") +
  coord_flip() +
  scale_y_continuous(labels = comma)
# count of large order is very low compared to medium and small sized orders

```

```{r}
#6.Top customer country:

#Which country is the most frequent customer?
#Which country generates the most revenue?
round(prop.table(table(df$COUNTRY))*100,1)
summary(df)
# USA, Spain, France, Australia, UK - top 5 customers
# ireland, philippines, switzerland - bottom 3 customers
```
```{r}

# 7. How do sales vary by country:

#Which country has the highest average sales per order?
#Which country has the lowest average sales per order?
# Create a new factor variable with the initials of the country names
df$COUNTRY_Initials = as.factor(df$COUNTRY)

# Set the levels of the factor variable to all 24 countries
levels(df$COUNTRY_Initials) = unique(df$COUNTRY)
ggplot(df, aes(x=COUNTRY_Initials, y=SALES, fill=COUNTRY_Initials)) +
  geom_bar(stat="summary", fun="mean") +
  facet_wrap(~PRODUCTLINE, scales="free_y", ncol=2) +
  labs(title="Average sales for different product lines per country", x="Country", y="Average Sales") +
  scale_x_discrete(labels = abbreviate) +
 theme(axis.text.x = element_text(angle=90, hjust = 1))

# country-wise average sales does not vary by a lot, contained within 3000-4000
# Denmark has the highest average sales, while Canada has lowest
```


```{r}
# 8.Which country has the highest orders cancelled?
#Which country has the highest cancellation rate for orders?
#What factors might contribute to this high cancellation rate?
status.df = df %>% group_by(COUNTRY, STATUS) %>% summarise(Count = n()) %>% spread(STATUS, Count, fill = 0)
status.df = cbind.data.frame(status.df, total=rowSums(status.df[,c(2:7)]))
status.df
round((status.df$Cancelled/status.df$total)*100,2)

# Spain's cancellation rate  = 4.68%
# Sweden's cancellation rate = 28.07%
# UK's cancellation rate     = 9.72%
# USA's cancellation rate    = 1.51%

```
```{r}
# 9.What product lines are ordered by Sweden?
#Which product lines are most frequently ordered by Sweden?
#What is the overall order pattern for Sweden?
sweden_orders = df[df$COUNTRY=='Sweden',]
table(sweden_orders$PRODUCTLINE)
table(sweden_orders$DEALSIZE)
table(sweden_orders$STATUS)

large_orders = df[df$DEALSIZE=='Large',]
summary_table = large_orders %>% group_by(COUNTRY, PRODUCTLINE) %>% summarise(TotalSales=sum(SALES)) %>% arrange(desc(TotalSales))
# USA places highest large-sized orders for classic cars, followed by France
# heatmap
ggplot(summary_table, aes(x=COUNTRY, y=PRODUCTLINE, fill=TotalSales))+
  geom_tile()+
  labs(title='Total Sales - Large Order size by Country and product line', x='Country',y='Product Line')+
  theme(axis.text.x = element_text(angle=45, hjust = 1))
# out of 57 orders placed, 16 cancelled and 6 on hold, i.e. about 38-39% orders not fulfilled
# if we get the cost structure of the firm, we can decide on eliminating Sweden as a customer if it leads to losses
# or brings down business efficiency
# alternatively, we can investigate reasons for cancellation
```


```{r}
# 11.Sales over time of different product lines:
#How did sales for each product line vary over the 3-year period?
#Were there any trends or changes in sales patterns for different product lines?
ggplot(df, aes(x = ORDERDATE, y = SALES, group = PRODUCTLINE)) +
  geom_line() + facet_wrap(~PRODUCTLINE, scales = "free_y", ncol = 2) +
  labs(title = "Sales Over Time for Different Product Lines", x = "Order Date", y = "Sales")

```
```{r}
# 12. Which product line has the highest sales over different years?
#Which product line consistently has the highest sales across the 3 years?
#Which product line has the lowest sales across the 3 years?
df$year = year(df$ORDERDATE)
df_with_year = df %>%
  group_by(year, PRODUCTLINE) %>%
  summarise(TotalSales = sum(SALES)) %>%
  filter(TotalSales == max(TotalSales))

df_with_year %>%
  group_by(year)
# classic cars has the highest sales in all 3 years
# trains have the lowest sales in all 3 years 


```

```{r}
#16.Sales by month:
#How do sales vary by month within each year?
#Are there any seasonal patterns in sales?
# format the order date
df$MONTH = month(df$ORDERDATE)

# calculate monthly sales
monthly_sales = df %>% group_by(MONTH) %>% summarize(TotalSales = sum(SALES))

# plot monthly sales
ggplot(monthly_sales, aes(x = MONTH, y = TotalSales)) + geom_line()+
  # add month name on x axis
  labs(x = "Month")
```
```{r}

#17.Correlation between sales and order date:
#Is there any correlation between the date an order is placed and the amount of the order?
#Could this be due to seasonal factors or other factors?

# Convert ORDERDATE to numeric
df$ORDERDATE = as.numeric(df$ORDERDATE)

# calculate correlations
correlations = df %>% select(SALES, ORDERDATE) %>% cor()

# print correlations
print(correlations)
```
```{r}

#18.Correlation between sales and customer country:
#Is there any correlation between the country an order is placed from and the amount of the order?
#Could this be due to factors such as economic conditions or cultural preferences?

# Convert COUNTRY to numeric
df$COUNTRY = as.numeric(df$COUNTRY)

# Convert ORDERDATE to numeric
df$ORDERDATE = as.numeric(df$ORDERDATE)

# calculate correlations
correlations = df %>% select(SALES, COUNTRY) %>% cor()

# print correlations
print(correlations)
```
```{r}
#19.Correlation between sales and deal size:
#Is there any correlation between the deal size of an order and the amount of the order?
#Could this be due to factors such as the complexity of the order or the perceived value?



df$DEALSIZE_NUM = as.numeric(df$DEALSIZE) - 1

# calculate correlations
correlations = df %>% select(SALES, DEALSIZE_NUM) %>% cor()

# print correlations
print(correlations)


```
```{r}
#20.Sales by deal size and product type:
#How do the distribution of deal sizes vary for different product types?
#Are there any patterns or trends in the distribution of large orders for different product types?
# Calculate sales by deal size and product type
sales_by_deal_size_and_product_type = df %>%
  group_by(DEALSIZE, PRODUCTLINE) %>%
  summarize(TotalSales = sum(SALES))

# Use geom_col() to plot data by multiple variables
ggplot(sales_by_deal_size_and_product_type, aes(x = DEALSIZE, fill = PRODUCTLINE, y = TotalSales)) +
  geom_col() +
  facet_wrap(~PRODUCTLINE)
```


